ALLINONE4298/Hacktober2021

- Languages/C++/Hello.cpp
- Languages/C/Hello.c
Add Languages folder to add programs to separate folders
> Add Languages folder

- Languages/C++/countDigitsInNumber.cpp
> added file in c++ folder

- Languages/Python/downloads-organizer.py
I have added a download files organizer with a simple python script!
> Added a download organizer program with python.

- CONTRIBUTORS.md
- Languages/C++/Hello.cpp
- Languages/C++/countCharacter.cpp
Added a new C++ program that counts a occurrences of a character inside a string and added myself to the contributors file
> added new characterCount.cpp and fixed a bug in Hello.cpp

- Languages/C/toggle case in string
Hey i  have add a new file for toggling cases in string.
> Toggle case in string

- Languages/C/factorial_using_recursion.c
Find factorial of a given number
> factorial_using_recursion.c

- Languages/Java/SearchBinaryTree with custom LinkedList/ListiItem.java
- Languages/Java/SearchBinaryTree with custom LinkedList/Main.java
- Languages/Java/SearchBinaryTree with custom LinkedList/MyLinkedList.java
- Languages/Java/SearchBinaryTree with custom LinkedList/Node.java
- Languages/Java/SearchBinaryTree with custom LinkedList/NodeList.java
- Languages/Java/SearchBinaryTree with custom LinkedList/SearchTree.java
Binary Search Tree using LinkedList written by me.
> BinarySearchTree with custom LinkedList in Java

- Languages/Python/hangman_game.py
Python Hangman game for Hacktober2020
> Hangman Game

- CONTRIBUTORS.md
- Languages/Python/triangle_pattern.py
> a simple triangle pattern in python

- Languages/C++/catalan.cpp
> catalan.cpp

- CONTRIBUTORS.md
- Languages/C/area of triangle.c
- mayur.json
a valuable contribution to the project
> Contribute

- Languages/C++/Boboniu Likes to Color Balls.cpp
- Languages/C++/Mex Subset.cpp
These are some problems from Codeforces.
> Added Some good beginner friendly problems

- Languages/C++/BalancedParanthesis.cpp
- Languages/C++/BinaryTreeClass.cpp
- Languages/C++/CheckPrimebyFunction.cpp
- Languages/C++/LinkedListAppend.cpp
- Languages/C++/LinkedLists.cpp
- Languages/C++/PowerByRecursion.cpp
- Languages/C++/QuadraticRoots.cpp
- Languages/C++/QueueUsingArray.cpp
- Languages/C++/ReverseAQueue.cpp
- Languages/C++/RotateString.cpp
- Languages/C++/SearchingSortingAlgo.cpp
- Languages/C++/Stack.cpp
- Languages/C++/Vectors.cpp
Added code for different programs in C++ folder of Languages.
> added code for different programs in cpp

- Languages/C++/TicTacToe.cpp
Added Tictactoe game in c++ :  its made with most basic stuff like loops and conditional statements
> Added Tictactoe game in c++

- Languages/Javascript - html/validation.html
Created a basic webpage for Username and Password Validation using HTML and Javascript.
> Username and Password Validation

- Languages/C/Balanced_Parenthesis.c
This code explains step by step process of balanced parenthesis problem.
> Created matching_parenthesis.c

- Languages/C++/Bubble-Sort.cpp
Added Bubble-Sort in C++ Language.
please accept and merge my PR.
> Added Bubble-Sort

- Languages/C++/fenwick.cpp
c++ code for Fenwick tree data structure has been added
> fenwick tree added

- Languages/Java/second_largest.java
> Created second_largest.java

- Web Apps/Weather App/app.js
- Web Apps/Weather App/index.html
- Web Apps/Weather App/package-lock.json
- Web Apps/Weather App/package.json
This folder/file is for HacktoberFest 2020. Submitted by Siddhesh Shinde.
> Web app for Weather using API

- Languages/Python/Longest_increasing_subsequence.py
Solved in the most optimal way, using the concept of dynamic programming.
>  Longest Increasing Subsequence Problem solved with explanation

- Languages/C/memoalloc.C
Hey There,
I have added dynamic memory allocation and reallocation using c programming.
> added dynamic memory allocation and reallocation using c

- Languages/C/BinarySearchTree.c
Added a binarySearchTree program in c
> Added binarySearchTree in C

- Languages/Java/radialboundary.java
I am new to open source and thankyou for the opportunity. Please merge my PR
> enhanced for loop radial pattern programming java

- Languages/C++/LinkedList_AppendNode.cpp
> Add A NODE TO LINKED LIST

- Languages/C++/CiircularQueueusingArray.cpp
- Languages/C++/ReverseStack.cpp
Added -
1) Circular Queue using Array
2) Reverse a Stack
> Add C++ DSA Codes

- Languages/C++/Contacts(hackerrank).cpp
Implement using Trie data structure
> Added Hackerrank problem (Contacts)

- CONTRIBUTORS.md
- Languages/C/DiamondPattern.c
I have added a C progam of diamond structure
> Added a C program of diamond structure

- Languages/Java/mergeSortedLists.java
> Added mergeSortedLists.java

- Languages/Python/insertionSort.py
- Languages/Python/matrixMultiplication.py
- Languages/Python/selectionSort.py
- Languages/Python/sqrtUsingNewtonMethod.py
-> added selection and insertion sort
-> added matrix multiplication
-> added find sqrt using newton method
> Added some more python programs

- Languages/Python/commandLineArg.py
- Languages/Python/jumpSearch.py
- Languages/Python/powerOfANumber.py
-> add a program to find power of a number
-> add a program to implement jump search
-> add a program to take command line arguments
> add power of number, jump search and command line arg program in python

- Languages/C++/BuildTree_fromPre&Postorder.cpp
- Languages/C++/BuildTree_fromPre&inorder.cpp
- Languages/C++/Find mex in a tree.cpp
- Languages/C++/Flatten a binary tree.cpp
- Languages/C++/LCA.cpp
Some Problems have only algo(Interviewbit input function) without user input and final output printing
> Added Tree Problems

- Languages/Java/AotiConverter.java
This is a Java Function Class which contains Aoti Function similar to those present in C/C++ library.
This will Conver your String to an Integer with predefined set of rules for conversion. 
eg: "123" -> 123, "0032" -> 32
> Adding Aoti Function to Convert Strings

- Languages/C/X_shape.C
created a c program which prints the X shape pattern of numeric digits
> Created X_shape.C

- Languages/Python/fibonacci.py
please accept my PR. added a fibonacci python based language file in respected folder.
> added a python code file

- Languages/C++/dijikstra.cpp
dijikstra shortest path algorithm in CPP
> added CPP dijikstra shortest path algorithm

- Languages/C/swapping with pointer without 3rd var.c
Swap Funtion without using third variable. with use of pointer.
> Create swapping with pointer without 3rd var.c

- Languages/Python/hangman.py
CLI Hangman game. Draws and updates hanging man figure.
> Hangman Game with Python

- Languages/Javascript - html/CPU_Scheduling_Algos/fcfs.html
- Languages/Javascript - html/CPU_Scheduling_Algos/index.html
- Languages/Javascript - html/CPU_Scheduling_Algos/pnp.html
- Languages/Javascript - html/CPU_Scheduling_Algos/pp.html
- Languages/Javascript - html/CPU_Scheduling_Algos/rr.html
- Languages/Javascript - html/CPU_Scheduling_Algos/sjf.html
- Languages/Javascript - html/CPU_Scheduling_Algos/srtf.html
Added CPU Scheduling Algorithms Website with Bootstrap.
> Add CPU Scheduling Algorithms

- Languages/C/BinarySearchForDescendingArray.c
Added Code For Binary Search Tree For Descending Array In C
> Added Code For Binary Search Tree For Descending Array

- CONTRIBUTORS.md
- Languages/Python/calculator.py
Simple Calculator Python
-  Enter Choice
- 1.Add 2.Subtract 3. Multiply 4.Divide ('1', '2', '3', '4')
- Enter Two Values
-  Get Answer
- Next Calculation : (yes/no)
> Calculator made with Python 3.

- Languages/Python/spin.py.py
pip install turtle from command prompt
> spin the spinner using 's' on keyboard

- Languages/C++/graph-dfs-bfs.cpp
Added BFS and DFS implementation of a graph(using adjacency matrix)
> Added graph-dfs-bfs.cpp file

- Languages/Python/resize.py
Hello,
I've added my bulk image resizer
> Added bulk image resizer

- Languages/Java/MooreVotingalgorithm.java
Find majority elemnt in O(1) space and O(n) time complexity in the given array.
> Moore's Voting algorithm

- Mini Projects/Food_Order/Food_Order.cpp
- Mini Projects/Food_Order/readme.md
I have mini project of online food ordering system using c++.
> Food Ordering System

- Languages/C++/Reverse using stack.cpp
reverse content in array with the help of stack
> Create Reverse using stack.cpp

- Languages/Python/Library_management_system.py
I have created a CLI project of a library management system it has some basic features and it is made using python
> Added a library management system CLI project

- Mini Projects/Python Language translator/pythonLanguageTranslator.py
Python Language Translator :It converts text from one language to another.
Hacktober Fest 2021
> pythonLanguageTranslator.py
